### ISSUE TITLE
question

### ISSUE THREAD

**Issue by nickdesaulniers** [stackgl/gl-quat#1]
Hiya! I think it's neat how you can do `require('gl-quat/slerp')` and only get the one function you actually need.  I think this is the basis for 'include only what you use' in JS, since we don't have a linker to pull in only what we need.  I see what's going on in the index.js file, with numerous requires.  Is that something NPM does? I couldn't find documentation on that feature; if there is some, can you point me in the right direction?

Wouldn't all of those require's occur at once, or does browserify handle the pruning of unused requires?

**Comment by yoshuawuyts** [comment]
npm expects a `main` file to always be present (defaults to `index.js`). Some modules such as [`send-data`](https://github.com/Raynos/send-data/blob/master/index.js) default to the simplest module in the library available, but the approach in `gl-quat` is also possible (and more common). 

Does that answer your question?

**edit**: FWIW I agree with you that the `module/submodule` approach is cleaner.

**Comment by mattdesl** [comment]
The `index.js` is just for user convenience, and we manually maintain the file. This way users can do:

``` js
var quat = require('gl-quat')
var slerp = quat.slerp
var mul = quat.multiply
```

However, it brings in _all_ of the `gl-quat` functions to your bundle. So `require('gl-quat/slerp')` is suggested to reduce final bundle size.

When ES6 becomes prevalent this trend might change; the `import` statements were designed to be statically analyzable to remove dead code.

**Comment by nickdesaulniers** [comment]
Neat, so I take it by [this high level overview](https://nodejs.org/api/modules.html#modules_all_together) `require('gl-quat/slerp')` is parsed as:
1. LOAD_NODE_MODULES('gl-quat')
2. LOAD_AS_FILE('gl-quat/slerp')
3. If 'gl-quat/slerp.js' is a file, load 'gl-quat/slerp.js' as JavaScript text.  STOP

I'm also curious as to what will happen with ES6 imports.  Thanks for the info!
